# global_costmap:
#     global_costmap:
#         ros__parameters:
#             update_frequency: 1.0
#             publish_frequency: 1.0
#             global_frame: map
#             robot_base_frame: base_link
#             # use_sim_time: True
#             robot_radius: 



local_costmap:
    local_costmap:
        ros__parameters:
            update_frequency: 5.0
            publish_frequency: 2.0
            always_send_full_costmap: True
            global_frame: odom
            robot_base_frame: base_link
            use_sim_time: True
            rolling_window: true
            width: 3
            height: 3
            resolution: 0.05
            robot_radius: 0.25 # TODO: get a real number in here
            plugins: ["voxel_layer", "inflation_layer"]
            voxel_layer:
                plugin: "nav2_costmap_2d::VoxelLayer"
                enabled: True
                publish_voxel_map: True
                origin_z: 0.0
                z_resolution: 0.05
                z_voxels: 16
                max_obstacle_height: 2.0
                mark_threshold: 0
                observation_sources: scan
                scan:
                    topic: /rookie/lidar/scan
                    max_obstacle_height: 2.0
                    clearing: True
                    marking: True
                    data_type: "LaserScan"
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 3.0
                inflation_radius: 0.5