#!/usr/bin/env python3

from enum import Enum, unique

from typing import TypeVar

uint32 = int
uint8 = int
string = str

DELIM: str = " "
END: str = "\n"

M = TypeVar("M", bound="Message")


class Message:
    class MESSAGE_TYPE(Enum):
        COMMAND = 1
        STATUS = 2

    name: str = ""
    id: str = ""
    _fields: list = []

    def pack(self, msg_type: MESSAGE_TYPE) -> bytes:
        msg: str = f"{self.id}"
        if msg_type is Message.MESSAGE_TYPE.COMMAND:
            msg += ".C"
        elif msg_type is Message.MESSAGE_TYPE.STATUS:
            msg += ".S"
        else:
            raise Exception("Invalid message type.")

        for field in self._fields:
            val: str = str(getattr(self, field[0]))
            msg += f"{DELIM}{val}"
        msg += END

        return bytes(msg, encoding="utf-8")

    @classmethod
    def unpack(cls: type[M], data: bytes) -> M:
        decoded: str = data.decode(encoding="utf-8").rstrip()
        split: list[str] = decoded.split(DELIM)

        # Strip the ID out, if it's there.
        if cls.id in split[0]:
            split = split[1:]

        print(split)
        constructor_params: dict = {}
        for idx, field in enumerate(split):
            field_name: str = cls._fields[idx][0]
            field_type: type = cls._fields[idx][1]

            if issubclass(field_type, Enum):
                field = int(field)

            field_value = field_type(field)

            constructor_params[field_name] = field_value

        message: Message = cls(**constructor_params)
        return message


class Motors(Message):
    """Motors message. Autogenerated on 2025-03-07 14:39:35.642200"""

    name: str = "Motors"
    id: str = "$MTR"

    @unique
    class DIRECTION(Enum):
        FORWARD = 0
        REVERSE = 1

        def __str__(self) -> str:
            return str(self.value)

    _fields = [
        ("motor_1_direction", DIRECTION),
        ("motor_1_pwm", uint8),
        ("motor_2_direction", DIRECTION),
        ("motor_2_pwm", uint8),
    ]

    def __init__(
        self,
        motor_1_direction: DIRECTION,
        motor_1_pwm: uint8,
        motor_2_direction: DIRECTION,
        motor_2_pwm: uint8,
        # /,  # positional args only
    ) -> None:
        self.motor_1_direction = motor_1_direction
        self.motor_1_pwm = motor_1_pwm
        self.motor_2_direction = motor_2_direction
        self.motor_2_pwm = motor_2_pwm


mtrs = Motors(Motors.DIRECTION.FORWARD, 0, 1, motor_2_pwm=0)
beets = mtrs.pack(Message.MESSAGE_TYPE.COMMAND)
mtrs2 = Motors.unpack(beets)
