<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- The plugins we need to be loaded -->
    <gazebo>
        <!-- plugin type "imu" -->
        <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu" />

        <!-- LiDAR ('gpu_lidar'), Camera ('camera') -->
        <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>
    
    <!-- "Global" sensors, not explicitly attached to any link -->
    <gazebo>
        <!-- Differential drive (skid steer) plugin -->
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <update_rate>30</update_rate>

            <left_joint>front_left_wheel_joint</left_joint>
            <left_joint>rear_left_wheel_joint</left_joint>
        
            <right_joint>front_right_wheel_joint</right_joint>
            <right_joint>rear_right_wheel_joint</right_joint>

            <wheel_separation>${track_width}</wheel_separation>
            <wheel_radius>${wheel_diameter / 2}</wheel_radius>

            <odom_publish_frequency>50</odom_publish_frequency>
            <frame_id>odom</frame_id>
            <!-- TODO: needs to be namespaced if I ever want more than one of these simulated simultaneously... -->
            <child_frame_id>base_link</child_frame_id>
            <!-- Internal gazebo topic, NOT ROS topic -->
            <topic>/model/rookie/cmd_vel</topic>

            <!-- TODO: I have no idea if this param is even doing anything...-->
            <max_wheel_torque>${drive_motor_torque_kg_cm / 2}</max_wheel_torque>
        </plugin>

        <!-- Joint state publishing -->
        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <!-- Internal gazebo topic, NOT ROS topic -->
            <topic>/model/rookie/state</topic>
            <update_rate>50</update_rate>
        </plugin>
    </gazebo>

    <!-- Sensors attached to the base_link -->
    <!-- <gazebo reference="base_link"> -->
    <gazebo reference="imu">
        <!-- <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu" /> -->
        <!-- IMU plugin -->
        <sensor name="imu_sensor" type="imu">
            <!-- Internal gazebo topic, NOT ROS topic -->
            <topic>/model/rookie/imu</topic>
            <!-- <frame_id>imu</frame_id> -->
            <!-- `frame_id` is correct for ROS Rolling, but since I'm being forced to use Jazzy now, I'm
                 stuck with gz_frame_id and/or ign_frame_id-->
            <gz_frame_id>imu</gz_frame_id>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>false</visualize>
        </sensor>
    </gazebo>

    <!-- Sensors attached to the lidar_slamtec_c1 link -->
    <gazebo reference="lidar_slamtec_c1">
        <sensor name="lidar_slamtec_c1_sensor" type="gpu_lidar">
            <pose relative_to='lidar_joint'>0 0 0 0 0 0</pose>
            <!-- Internal gazebo topic, NOT ROS topic -->
            <topic>/model/rookie/lidar</topic>

            <!-- `frame_id` is correct for ROS Rolling, but since I'm being forced to use Jazzy now, I'm
                 stuck with gz_frame_id and/or ign_frame_id-->
            <!-- <frame_id>lidar_slamtec_c1</frame_id> -->
            <gz_frame_id>lidar_slamtec_c1</gz_frame_id>
            
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                    <vertical>
                        <resolution>0.01</resolution>
                        <samples>1</samples>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                        <!--
                        <samples>32</samples>
                        <min_angle>-1.57</min_angle>
                        <max_angle>1.57</max_angle> 
                        -->
                    </vertical>
                </scan>
                <range>
                    <min>0.5</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

    <gazebo reference="camera">
        <sensor name="camera_sensor" type="camera">
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <width>320</width>
                    <height>240</height>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <!-- Internal gazebo topic, NOT ROS topic -->
            <topic>/model/rookie/camera</topic>
            <!-- `frame_id` is correct for ROS Rolling, but since I'm being forced to use Jazzy now, I'm
                 stuck with gz_frame_id and/or ign_frame_id-->
            <gz_frame_id>camera</gz_frame_id>
        </sensor>
    </gazebo>

</robot>